openapi: "3.0.1"
info:
  title: "Knowledge Base Verification Credential Issuer Api"
  version: "1.0"

paths:
  /session:
    post:
      responses:
        "201":
          description: "201 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "500 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - sigv4: [ ]
      x-amazon-apigateway-integration:
        credentials: "arn:aws:iam::*:user/*"
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${KBVSessionFunction.Arn}/invocations"
        passthroughBehavior: "when_no_match"
components:
  securitySchemes:
    sigv4:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "awsSigv4"
  schemas:
    Session:
      required:
        - "session_id"
      type: "object"
      properties:
        session_id:
          type: "string"
    Error:
      title: "Error Schema"
      type: "object"
      properties:
        message:
          type: "string"