AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  di-ipv-cri-kbv-api
  SAM Template for the kbv api

Globals:
  Api:
    Auth:
      DefaultAuthorizer: AWS_IAM
  Function:
    Timeout: 60

Resources:

  KBVSessionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        InvokeRole: CALLER_CREDENTIALS

  KBVSessionTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "kbv-session-${AWS::StackName}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "sessionId"
          AttributeType: "S"
        -
          AttributeName: "authorizationCode"
          AttributeType: "S"
        -
          AttributeName: "token"
          AttributeType: "S"
        -
          AttributeName: "questionState"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "sessionId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        -
          IndexName: "authorization-code-index"
          KeySchema:
            -
              AttributeName: "authorizationCode"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "sessionId"
            ProjectionType: "INCLUDE"
        -
          IndexName: "token-index"
          KeySchema:
            -
              AttributeName: "token"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "sessionId"
            ProjectionType: "INCLUDE"
        -
          IndexName: "questions-index"
          KeySchema:
            -
              AttributeName: "questionState"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "sessionId"
            ProjectionType: "INCLUDE"


  KBVSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: uk.gov.di.ipv.cri.kbv.api.handler.SessionHandler::handleRequest
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - DynamoDBWritePolicy:
            TableName: !Ref KBVSessionTable
      Runtime: java11
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          IS_LOCAL: false
          KBV_SESSION_TABLE_NAME: !Ref KBVSessionTable
          POWERTOOLS_SERVICE_NAME: di-ipv-cri-kbv-api
          EXPERIAN_API_WRAPPER_SAA_RESOURCE: http://localhost:8080/question-request
          EXPERIAN_API_WRAPPER_RTQ_RESOURCE: http://localhost:8080/question-answer
          EXPERIAN_API_WRAPPER_URL: http://localhost:8080/
      Events:
        KBVSessionApi:
          Type: Api
          Properties:
            Path: /session
            Method: Post
            RestApiId: !Ref KBVSessionApi
            Auth:
              Authorizer: AWS_IAM

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  KBVSessionApi:
    Description: "API Gateway endpoint URL for Dev KBVSession function"
    Value: !Sub "https://${KBVSessionApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/session/"
  KBVSessionFunction:
    Description: "KBVSession check lambda function ARN"
    Value: !GetAtt KBVSessionFunction.Arn
  KBVSessionFunctionIamRole:
    Description: "Implicit IAM Role created for KBVSession function"
    Value: !GetAtt KBVSessionFunction.Arn
  
