AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  di-ipv-cri-kbv-api
  SAM Template for the kbv api

Globals:
  Api:
    Auth:
      DefaultAuthorizer: AWS_IAM
  Function:
    Timeout: 60

Resources:

  CriSessionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        InvokeRole: CALLER_CREDENTIALS

  CriSessionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: session
      PrimaryKey:
        Name: id
        Type: String

  CriSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: uk.gov.di.ipv.cri.kbv.api.handler.SessionHandler::handleRequest
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
      Runtime: java11
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: di-ipv-cri-kbv-api
          EXPERIAN_API_WRAPPER_SAA_RESOURCE: http://localhost:8080/question-request
          EXPERIAN_API_WRAPPER_RTQ_RESOURCE: http://localhost:8080/question-answer
          EXPERIAN_API_WRAPPER_URL: http://localhost:8080/
      Events:
        CriSessionApi:
          Type: Api
          Properties:
            Path: /session
            Method: Post
            RestApiId: !Ref CriSessionApi
            Auth:
              Authorizer: AWS_IAM

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CriSessionApi:
    Description: "API Gateway endpoint URL for Dev CriSession function"
    Value: !Sub "https://${CriSessionApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/session/"
  CriSessionFunction:
    Description: " CriSession check lambda function ARN"
    Value: !GetAtt CriSessionFunction.Arn
  CriSessionFunctionIamRole:
    Description: "Implicit IAM Role created for CriSession function"
    Value: !GetAtt CriSessionFunction.Arn